### ISSUE TITLE
关于换架构后多语言翻译

### ISSUE THREAD

**Issue by shuixxing233** [dyang886/Game-Save-Manager#10]
我现在在帮忙写软件的日语化翻译，但是我看到作者之前说要准备换架构了，所以我想问一下，我现在还有必要写吗？（现在目前是写了一半）

**Comment by dyang886** [comment]
换Qt后翻译框架不变，所以可以写的，感谢！

**Comment by shuixxing233** [comment]
> 换Qt后翻译框架不变，所以可以写的，感谢！
