### ISSUE TITLE
[Feature]默認自啟

### ISSUE THREAD

**Issue by NeKoOuO** [dyang886/Game-Save-Manager#4]
因為每次改完設定都需要自啟
但是默認是不自動重啟的 要關掉好幾個視窗非常繁瑣
可以將確定按鈕改成默認重啟 並增加一個稍後重啟的選項

**Comment by dyang886** [comment]
软件重启仅针对语言设置，由于更改设置不属于频繁操作且重启不好实现，暂不考虑更改
（其实你只需要关闭主程序界面，设置界面会被自动关闭）
