### ISSUE TITLE
.gsm文件恢复出错后无法继续恢复

### ISSUE THREAD

**Issue by Goojoe** [dyang886/Game-Save-Manager#6]
![image](https://github.com/dyang886/Game-Save-Manager/assets/78355492/d7e48b89-9bd3-4f04-8f24-8e640d786aca)

通过.gsm文件恢复出错，程序会卡死。恢复日志只有 `正在解压文件...` 很难判断问题。将.gsm文件复制到本地后恢复正常

**Comment by dyang886** [comment]
可以的话麻烦提供一下出错的.gsm文件

**Comment by Goojoe** [comment]
[0 Custom.zip](https://github.com/dyang886/Game-Save-Manager/files/14430080/0.Custom.zip)
请解压一次获得.gsm文件

**Comment by dyang886** [comment]
1.1.4 应该已解决

**Comment by Goojoe** [comment]
![image](https://github.com/dyang886/Game-Save-Manager/assets/78355492/5c68f1ac-7b7e-440b-afb3-a9211bf7da0d)
[0 Custom.zip](https://github.com/dyang886/Game-Save-Manager/files/14443527/0.Custom.zip)
报告删除备份错误

**Comment by dyang886** [comment]
已修复，重下1.1.4
