### ISSUE TITLE
当游戏不存在时，之前备份的存档会被覆盖删除

### ISSUE THREAD

**Issue by Goojoe** [dyang886/Game-Save-Manager#8]
第一次备份
0 Custom
Human_Fall Flat
Stray
Terraria
Terraria#

重装系统恢复第一次备份后的第二次备份
0 Custom
Stray
Terraria

也就是没检测到的游戏会被直接覆盖删除？

**Comment by dyang886** [comment]
这是因为有些游戏存档位置在 Steam/Ubisoft/游戏安装路径 所以如果没安装的话就无法恢复
每次备份均会抹除上次备份（指备份路径下所有备份），所以第二次备份时之前无法还原的游戏就没有被备份
为改善这种情况，现在恢复失败时会在文字框内提醒哪个游戏恢复失败了

**Comment by Goojoe** [comment]
恢复失败还会删除备份吗

**Comment by dyang886** [comment]
恢复时只会恢复，不会删除备份。但是要是有些恢复失败之后再备份的话之前备份还是会被删除的。总之每次备份均会抹除上次备份需注意

**Comment by Goojoe** [comment]
还是会被删除的，那可以保留吗

**Comment by Goojoe** [comment]
还有一个问题，为什么导出相比备份那么慢，是最高等级压缩吗？如果是，能否增加选项压缩等级和改用7zip压缩

**Comment by dyang886** [comment]
> 还是会被删除的，那可以保留吗

这个得涉及到每个游戏存档单独管理，以后再说

**Comment by dyang886** [comment]
> 还有一个问题，为什么导出相比备份那么慢，是最高等级压缩吗？如果是，能否增加选项压缩等级和改用7zip压缩

压缩用的python默认的zipfile，由于导出不属于频繁操作，暂不考虑增加额外选项

**Comment by Goojoe** [comment]
如果仅仅是在本地备份，导出确实不频繁。但是我还会在每次备份后上传到云盘。零碎文件上传肯定是没有压缩包快的

**Comment by dyang886** [comment]
这个后续我看看有没有更快速的压缩

**Comment by Goojoe** [comment]
机械硬盘性能太差了，这样压缩要非常久，很需要仅打包选项。真不缺压缩的那点空间。更快的压缩可以用zstd

**Comment by dyang886** [comment]
你说的仅打包是指整个备份存储文件夹？这样的话可以直接拷贝整个备份存储路径
然后的话软件正在准备一个大更新，可以单独操作每个游戏，每个游戏也可进行多个备份，挺复杂的要一些时间。UI预览：
![Screenshot 2024-05-05 105708](https://github.com/dyang886/Game-Save-Manager/assets/88755186/2580bc7b-57eb-4599-a133-49e6dd804df2)

**Comment by Goojoe** [comment]
对，说的就是那个。
还有从.gsm恢复还是会卡住，解压出来恢复不会

**Comment by dyang886** [comment]
现在可单选个别游戏且可保留多个备份
